language: python
sudo: false
cache: pip

addons:
  postgresql: "9.2" # minimal postgresql version for the daterange method
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - unixodbc-dev
      - python-mysqldb

env:
  global:
  - VERSION="saas-18" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: Z06mZCN+Hm3myqHSOZpOOk1pd4oq1epAWZv6m9OX2bTNHbhyOVOGK6JWWsnDm/3DUCN1ZeLtSGOl9bvQfMa8ahQHA80MkLL16YlTvQV59Lh+L2gAYmxX+ogJCJgeQSVAXlGLscgkADCu/HzDlmatrDeROMtULn5i23j2qcyUNyM=
  - COUNTRY="MX"

matrix:
  include:
    - python: 2.7
      env:
        LINT_CHECK="1"
    - python: 3.4
      env:
        TRANSIFEX="1"
    - python: 3.4
      env:
        TESTS="1" ODOO_REPO="odoo/odoo"
    - python: 3.4
      env:
        TESTS="1" ODOO_REPO="OCA/OCB" VERSION="11.0"

install:
  - git clone --single-branch --depth=1 https://github.com/OCA/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  # Install libraries that require specific development headers, but not during lint test ## The following package is not complatibility to python3
  #- if ! [ "$LINT_CHECK" = "1" ]; then pip install pymssql MySQL-python pyodbc; fi
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
  - ln -s ${TRAVIS_BUILD_DIR}/server_environment_files_sample ${TRAVIS_BUILD_DIR}/server_environment_files
script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
